services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: setlist_generator
      POSTGRES_USER: postgres
      # セキュリティ強化: 環境変数から読み込み、デフォルトは削除
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_dev_only}
      # セキュリティ強化: SSL設定
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      # セキュリティ強化: ローカルホストのみバインド
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # セキュリティ強化: コンテナ権限制限
    user: "999:999"
    # セキュリティ強化: 読み取り専用ルートファイルシステム
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    # セキュリティ強化: ネットワーク分離
    networks:
      - setlist_network
    # セキュリティ強化: リソース制限
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # セキュリティ強化: ヘルスチェック
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d setlist_generator"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # セキュリティ強化: ログ設定
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# セキュリティ強化: カスタムネットワーク
networks:
  setlist_network:
    driver: bridge
    internal: false  # 開発環境のためfalse（本番では true に変更）

volumes:
  postgres_data:
    # セキュリティ強化: ボリューム暗号化（Dockerで利用可能な場合）
    driver: local