import React from 'react'
import { Box, Typography, Paper } from '@mui/material'
import { SetlistThemeProps } from './types'
import { formatEventDateJST } from '@/lib/dateUtils'

export const WhiteTheme: React.FC<SetlistThemeProps> = ({ data, className }) => {
  const { bandName, eventName, eventDate, openTime, startTime, items, qrCodeURL } = data

  // A4 dimensions: 210mm x 297mm (roughly 794px x 1123px at 96 DPI)
  const A4_WIDTH = 794
  const A4_HEIGHT = 1123

  // Dynamic font size based on number of songs for A4 compatibility
  const getFontSize = (count: number): string => {
    if (count <= 6) return '40px'
    if (count <= 8) return '34px'
    if (count <= 10) return '30px'
    if (count <= 12) return '26px'
    if (count <= 15) return '24px'
    if (count <= 18) return '22px'
    if (count <= 25) return '20px'
    return '18px'
  }

  const fontSize = getFontSize(items.length)

  return (
    <Paper
      className={className}
      sx={{
        backgroundColor: '#ffffff',
        color: '#000000',
        padding: '40px',
        width: `${A4_WIDTH}px`,
        height: `${A4_HEIGHT}px`,
        margin: '0 auto',
        position: 'relative',
        boxSizing: 'border-box',
        display: 'flex',
        flexDirection: 'column',
        fontFamily: 'Inter, system-ui, sans-serif',
        overflow: 'hidden',
        border: '2px solid #e0e0e0',
        borderRadius: 0,
      }}
    >
      {/* Header Section */}
      <Box sx={{ textAlign: 'left', mb: 6, pl: 2 }}>
        <Typography
          variant="h1"
          component="h1"
          sx={{
            fontSize: '48px',
            fontWeight: 700,
            color: '#000000',
            mb: 1,
            letterSpacing: '2px',
            textTransform: 'lowercase',
            lineHeight: 1.1,
          }}
        >
          {bandName}
        </Typography>

        {eventName && (
          <Typography
            variant="h2"
            sx={{
              fontSize: '18px',
              color: '#666666',
              mb: 3,
              fontWeight: 400,
              textTransform: 'uppercase',
              letterSpacing: '1px',
            }}
          >
            {eventName}
          </Typography>
        )}

        {/* Event Details */}
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5 }}>
          {eventDate && (
            <Typography sx={{ fontSize: '16px', color: '#000000', fontWeight: 400 }}>
              {formatEventDateJST(eventDate)}
            </Typography>
          )}
          <Box sx={{ display: 'flex', gap: 2 }}>
            {openTime && (
              <Typography sx={{ fontSize: '16px', color: '#000000', fontWeight: 400 }}>
                OPEN {openTime}
              </Typography>
            )}
            {startTime && (
              <Typography sx={{ fontSize: '16px', color: '#000000', fontWeight: 400 }}>
                START: {startTime}
              </Typography>
            )}
          </Box>
        </Box>
      </Box>

      {/* QR Code */}
      {qrCodeURL && (
        <Box
          sx={{
            position: 'absolute',
            top: 30,
            right: 30,
            width: 80,
            height: 80,
            border: '2px solid #e0e0e0',
            padding: '8px',
            borderRadius: '4px',
            backgroundColor: '#ffffff',
          }}
        >
          <img
            src={qrCodeURL}
            alt="QR Code"
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'contain',
            }}
          />
        </Box>
      )}

      {/* Songs List */}
      <Box
        sx={{
          flex: 1,
          overflow: 'hidden',
          pl: 2,
          display: 'flex',
          flexDirection: 'column',
          gap: 3.5,
        }}
      >
        {items.map(item => (
          <Box key={item.id} sx={{}}>
            <Typography
              sx={{
                fontSize: fontSize,
                color: '#000000',
                fontWeight: 400,
                lineHeight: 1.2,
                mb: item.note ? 0.5 : 0,
              }}
            >
              {item.title}
            </Typography>
            {item.note && (
              <Typography
                sx={{
                  fontSize: '16px',
                  color: '#666666',
                  fontWeight: 300,
                  pl: 0,
                }}
              >
                {item.note}
              </Typography>
            )}
          </Box>
        ))}
      </Box>

      {/* Footer */}
      <Box sx={{ mt: 'auto', pt: 2, textAlign: 'center', borderTop: '1px solid #e0e0e0' }}>
        <Typography sx={{ fontSize: '12px', color: '#999999' }}>
          Generated by mosquitone Emotional Setlist Studio
        </Typography>
      </Box>
    </Paper>
  )
}
